name: sage-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - compilers
  - make
  - m4
  - perl
  - python=3.11
  - tar
  - bc
  - appdirs
  - arb
  - boost-cpp
  - brial
  - bzip2
  - cddlib
  - cliquer
  - cmake
  - curl
  - distlib
  - ecl
  - eclib
  - ecm
  - fflas-ffpack
  - filelock
  - libflint
  - fplll
  - freetype
  - bdw-gc
  - gengetopt
  - gf2x
  - gfan
  - fortran-compiler
  - giac
  - givaro
  - glpk
  - gmp
  - gsl
  - iml
  - texinfo
  - lcalc
  - libatomic_ops
  - libbraiding
  - libffi
  - libgd
  - libhomfly
  - xz
  - libpng
  - linbox
  - lrcalc
  - m4ri
  - m4rie
  - mathjax
  - maxima
  - mpc
  - mpfi
  - mpfr
  - nauty
  - ncurses
  - ninja
  - ntl
  - openblas
  - blas=2.*=openblas
  - openssl
  - palp
  - pari=*=*_pthread
  - pari-elldata
  - pari-galdata
  - pari-galpol
  - pari-seadata
  - pari-galdata
  - pari-seadata-small
  - patch
  - patchelf
  - pkg-config
  - planarity
  - ppl
  - primecount
  - primesieve
  - qhull
  - readline
  - rw
  - singular
  - sqlite
  - suitesparse
  - symmetrica
  - sympow
  - tachyon
  - tox
  - virtualenv
  - xz
  - zeromq
  - zlib
  # Packages needed for ./bootstrap
  - autoconf
  - automake
  - libtool
  - pkg-config
  # Additional packages providing all dependencies for the Sage library
  - alabaster
  - appnope
  - argon2-cffi
  - asttokens
  - attrs
  - babel
  - backcall
  - beautifulsoup4
  - beniget
  - bleach
  - certifi
  - cffi
  - charset-normalizer
  - sagemath-db-combinatorial-designs
  - sagemath-db-conway-polynomials
  - cppy
  - cvxopt
  - cycler
  - cypari2
  - cysignals
  - cython
  - python-dateutil
  - decorator
  - defusedxml
  - deprecation
  - docutils
  - editables
  - sagemath-db-elliptic-curves
  - entrypoints
  - executing
  - python-fastjsonschema
  - flit-core
  - fonttools
  - fpylll
  - furo
  - gap-defaults>=4.12.2
  - gast
  - gmpy2
  - sagemath-db-graphs
  - hatchling
  - idna
  - imagesize
  - importlib_metadata
  - importlib-resources
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets<8.0.0
  - jedi
  - jinja2
  - jmol
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter-jsmol
  - jupyter_sphinx
  - jupyterlab_pygments
  - kiwisolver
  - python-lrcalc~=2.1
  - markupsafe
  - matplotlib>=3.5.1
  - matplotlib-inline
  - memory-allocator
  - mistune
  - mpmath
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx<3.0,>=2.4
  - notebook
  - numpy
  - packaging
  - pandocfilters
  - parso
  - pathspec
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgconfig
  - platformdirs
  - pluggy
  - ply
  - sagemath-db-polytopes
  - pplpy
  - primecountpy
  - prometheus_client
  - prompt_toolkit
  - pure_eval
  - py
  - pybind11
  - pycparser
  - pygments
  - pyparsing
  - pyrsistent
  - pythran
  - pytz
  - pytz-deprecation-shim
  - pyzmq
  - requests
  - rpy2
  - sagetex
  - scipy<1.11,>=1.5
  - send2trash
  - setuptools
  - setuptools_scm
  - setuptools
  - six
  - snowballstemmer
  - soupsieve
  - sphinx<8,>=5.2
  - sphinx-basic-ng
  - sphinx-copybutton
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-websupport
  - stack_data
  - sympy
  - terminado
  - threejs-sage=122.*
  - tinycss2
  - tomli
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - tzlocal
  - urllib3
  - vcversioner
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - zipp
  # Additional dev tools
  - autoconf
  - automake
  - libtool
  - pkg-config
  - openssh
  - pycodestyle
  - esbonio
  - git
  - gh
  - pytest
  - pytest-xdist
